apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.castService.port }}
    targetPort: {{ .Values.castService.port }}
  selector:
    app: cast-service
