apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.movieService.port }}
    targetPort: {{ .Values.movieService.port }}
  selector:
    app: movie-service
